version: '2'

services:
  rembg:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - bgapi
    restart: always
    volumes:
      - "./.u2net:/root/.u2net"



networks:
  bgapi:
    name: rembgapi